# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2a34e2a37c44b3f7779f8765ee44df6792619503fe2abe2cc44087686c9476db6ed4b500123251390154a93196b5fe020bca081c8dd1d6781d4afcf19fae8b2

test:
  secret_key_base: 67bad7034ffa5ef1f26182c20c88e4387b2f7de6375b993fdc2c4653092a22be9b9adb32134cfa42ed36d46b30fa99cd6d3c7e6032d39f425faf36384242538c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
